### ISSUE TITLE
Redirect to login page on bad_attributes_reject fail

### ISSUE THREAD

**Issue by syserr0r** [django-cas-ng/django-cas-ng#208]
Currently if a user is not allowed to login because of `bad_attributes_reject` then the user is presented with a 403 Forbidden page -- being able to redirect back to a login page (so they can see messages added by `bad_attributes_reject`) would be very useful.

**Comment by syserr0r** [comment]
It looks like this is what would need to be updated:
https://github.com/mingchen/django-cas-ng/blob/master/django_cas_ng/views.py#L125

**Comment by syserr0r** [comment]
I am currently working around this with the following code, for anyone who might be interested:

```python3
from django.core.exceptions import PermissionDenied
from django_cas_ng.views import login

def cas_login_wrapper(request, *args, **kwargs):
    try:
        return login(request, *args, **kwargs)
    except PermissionDenied:
        return redirect("/")
```
and then pointing my `urls.py` to `views.cas_login_wrapper` instead of `django_cas_ng.views.login`

**Comment by mingchen** [comment]
Closed as inactivity
