### ISSUE TITLE
I encounter problems when realizing  one app redirect other app  belong CAS server

### ISSUE THREAD

**Issue by niceyida** [django-cas-ng/django-cas-ng#212]
About follow three problems:
1.How to realize jumping between apps belong CAS server ,may i modify the CAS_PROXY_CALLBACK or CAS_ROOT_PROXIED_AS in setting.py ?
2.Where i should call the function of "Callback"?
3.I found that the table "django_cas_ng_proxygrantingticket" is empty.
Looking forward to your response，thanks！

**Comment by BarnabasSzabolcs** [comment]
Uhh, I don't understand what you've asked. Can you please write more details?
