### ISSUE TITLE
Unicode unaware downcase/upcase in a unicode string

### ISSUE THREAD

**Issue by danizen** [django-cas-ng/django-cas-ng#225]
The setting CAS_FORCE_CHANGE_USERNAME_CASE prompts the system to do a unicode naive down-case or upcase on the username returned by the CAS server.  This is implemented in django_cas_ng/backends.py in `clean_username`.

Similar code led to a CVE against Django which prompted [Django 2.2.9](https://docs.djangoproject.com/en/dev/releases/2.2.9/) and other releases today.

[This commit](https://github.com/django/django/commit/4d334bea06cac63dc1272abcec545b85136cca0e) shows the fix, and prompts me to believe django-cas-ng should do a similar Unicode normalization and case fold.

I don't think this is critical to be addressed right away - the CAS server is trusted in matters of authentication, and so we are not receiving a username from a completely untrusted party.

**Comment by danizen** [comment]
Note - I will follow up with a pull request sometime in future.

**Comment by mingchen** [comment]
PR is always welcome.

**Comment by mingchen** [comment]
Good read about this CVE!

CVE is related compare two unicode string in caseless match caused issue.
CAS_FORCE_CHANGE_USERNAME_CASE just change username to lowercase and there is no comparison happen, should not related to this CVE.

@danizen, Let me know if you thinking there is any potential vulnerability and proposal fix?

**Comment by mingchen** [comment]
Closed due to inactivity.
