### ISSUE TITLE
[Question] urls config

### ISSUE THREAD

**Issue by fbove** [django-cas-ng/django-cas-ng#239]
I have CAS running locally, my service is configured as follow:
```json
{
    "@class" : "org.apereo.cas.services.RegexRegisteredService",
    "serviceId" : "^(http|imap)://.*",
    "name" : "appname",
    "id" : 10000001,
    "evaluationOrder" : 10
}
```
After trying to login with default casuser, I'm getting this error on my app:

```bash
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='localhost', port=8443): Max retries exceeded with url: /cas/p3/serviceValidate?ticket=ST-4-DLDAucjE-jsXwuBO56DLJLj56p...
```

I've added this three lines on urls.py:
```python
    path('accounts/login', LoginView.as_view(), name='cas_ng_login'),
    path('accounts/logout', LogoutView.as_view(), name='cas_ng_logout'),
    path('accounts/callback', CallbackView.as_view(), name='cas_ng_proxy_callback'),
```
I guess I need to config `/cas/p3/` urls, is this correct? Is there a working example?

I've checked others inside [github.com/django-cas-ng](https://github.com/django-cas-ng/) without any luck.

Thanks!

**Comment by mingchen** [comment]
Which CAS protocol version your server use and what's your client config? You should dig more detail from server log. Checkout the protocol specification to get familiar with protocol: https://djangocas.dev/docs/4.0/CAS-Protocol-Specification.html

**Comment by fbove** [comment]
Thanks for the heads up.
It was a configuration issue which triggered a network issue.
My app is inside a docker container and it was trying to validate the ticket to a localhost CAS url.
