### ISSUE TITLE
CAS_RESPONSE_CALLBACKS not in official documentation

### ISSUE THREAD

**Issue by nottheswimmer** [django-cas-ng/django-cas-ng#242]
https://github.com/django-cas-ng/django-cas-ng/commit/77ee5672ca25f1642403dd7b71006929c15424da

I cannot find documentation for this feature on the official documentation page despite there being documentation in this PR.

**Comment by mingchen** [comment]
Thanks for reporting this issue. 

Please check the latest [configuration.html#cas-response-callbacks-optional](https://djangocas.dev/docs/4.0/configuration.html#cas-response-callbacks-optional):

**Comment by AmShaegar13** [comment]
Hi, this feature was reverted in #198. The current documentation is obsolete and should be removed as it's quite misleading. The CAS_RESPONSE_CALLBACKS setting never made it to any release.

**Comment by mingchen** [comment]
Thanks @AmShaegar13.

My bad, it was long time ago and forgot those PRs.

Removed CAS_RESPONSE_CALLBACKS from docs.
