### ISSUE TITLE
Please release CAS_FORCE_SSL_SERVICE_URL

### ISSUE THREAD

**Issue by daveseff** [django-cas-ng/django-cas-ng#245]
I wondered why the docs mentioned using CAS_FORCE_SSL_SERVICE_URL to force SSL but it wasn't working for me. 
I'm installing this into my docker container via pip, so I'm getting the latest release, 4.0.1 which does not include this feature. 

Can you please release this as soon as you can? 

Cheers,

**Comment by mingchen** [comment]
Sorry for confusion.

Released 4.1.0

**Comment by daveseff** [comment]
Thanks kindly.
