### ISSUE TITLE
CAS Group membership and permissions?

### ISSUE THREAD

**Issue by daveseff** [django-cas-ng/django-cas-ng#248]
I need the ability to restrict people in certain groups from using parts of my app.  I'm using mama-cas as my provider and have enabled mama_cas.callbacks.user_model_attributes callbacks. 

But I'm having difficulty figuring out how to access those attributes with django-cas-ng. I see that CAS_RESPONSE_CALLBACKS were removed in issue #242, so is this access some other way? 

Am I missing something?

**Comment by mingchen** [comment]
Per #242, CAS_RESPONSE_CALLBACKS is not working, you can make it work and PR is welcome.

Or you should able to get those attributes in `cas_user_authenticated` signal. checkout:
https://djangocas.dev/docs/latest/signals.html#django-cas-ng-signals-cas-user-authenticated

**Comment by daveseff** [comment]
@mingchen Thank you for that. I have seen that bit of documentation but I'm new to django signals. I was hoping you or someone would provide an example as to how to use this to provide authorization to my individual views. 

Perhaps a function decorator or something? 
Thanks.

**Comment by mingchen** [comment]
Checkout https://github.com/django-cas-ng/example/blob/master/mysite/signals.py
