### ISSUE TITLE
CAS_FORCE_SSL_SERVICE_URL = True don't work on LogoutView

### ISSUE THREAD

**Issue by jojo-80** [django-cas-ng/django-cas-ng#249]
**Platform & Version**
Platform: Windows or Linux or Mac...
django-cas-ng: 4.1.1
Django: 2.2.11
Python: 3.7.4
CAS Server Software and version:  4

**Describe the bug**
Hello,

I use the following options :
- CAS_FORCE_SSL_SERVICE_URL = True
- CAS_IGNORE_REFERER=True
- LOGOUT_REDIRECT_URL = '/'+BASE_URL_PATH+'........./'

On the Logout page, I am not redirected in HTTPS.

In the source code of django-cas-ng, the GET and POST methods of the LogoutView class do not call the get_service_url method which checks if CAS_FORCE_SSL_SERVICE_URL = True and initializes protocol = 'https'.

Thank.

**Comment by chunkai-meng** [comment]
Even I set the 
```
CAS_ROOT_PROXIED_AS = 'https://www.domain.co'
```
the LogoutView still redirects me to:
```
https://cas.domain.com/cas/logout?service=http%3A%2F%2Fwww.domain.co%3A443%2Fcheck-in
# decoded as:
https://cas.domain.com/cas/logout?service=http://www.domain.co:443/check-in
```

which result in an error in cas server:

```
Forbidden (Permission denied): /cas/logout
cas-prod    | Traceback (most recent call last):
cas-prod    |   File "/usr/local/lib/python3.7/site-packages/django/urls/base.py", line 75, in reverse
cas-prod    |     extra, resolver = resolver.namespace_dict[ns]
cas-prod    | KeyError: 'http'
cas-prod    |
cas-prod    | During handling of the above exception, another exception occurred:
cas-prod    |
cas-prod    | Traceback (most recent call last):
cas-prod    |   File "/usr/local/lib/python3.7/site-packages/mama_cas/utils.py", line 80, in redirect
cas-prod    |     to = reverse(to, args=args, kwargs=kwargs)
cas-prod    |   File "/usr/local/lib/python3.7/site-packages/django/urls/base.py", line 86, in reverse
cas-prod    |     raise NoReverseMatch("%s is not a registered namespace" % key)
cas-prod    | django.urls.exceptions.NoReverseMatch: 'http' is not a registered namespace
```

**Comment by chunkai-meng** [comment]
> Even I set the
> 
> ```
> CAS_ROOT_PROXIED_AS = 'https://www.domain.co'
> ```
> 
> the LogoutView still redirects me to:
> 
> ```
> https://cas.domain.com/cas/logout?service=http%3A%2F%2Fwww.domain.co%3A443%2Fcheck-in
> # decoded as:
> https://cas.domain.com/cas/logout?service=http://www.domain.co:443/check-in
> ```
> 
> which result in an error in cas server:
> 
> ```
> Forbidden (Permission denied): /cas/logout
> cas-prod    | Traceback (most recent call last):
> cas-prod    |   File "/usr/local/lib/python3.7/site-packages/django/urls/base.py", line 75, in reverse
> cas-prod    |     extra, resolver = resolver.namespace_dict[ns]
> cas-prod    | KeyError: 'http'
> cas-prod    |
> cas-prod    | During handling of the above exception, another exception occurred:
> cas-prod    |
> cas-prod    | Traceback (most recent call last):
> cas-prod    |   File "/usr/local/lib/python3.7/site-packages/mama_cas/utils.py", line 80, in redirect
> cas-prod    |     to = reverse(to, args=args, kwargs=kwargs)
> cas-prod    |   File "/usr/local/lib/python3.7/site-packages/django/urls/base.py", line 86, in reverse
> cas-prod    |     raise NoReverseMatch("%s is not a registered namespace" % key)
> cas-prod    | django.urls.exceptions.NoReverseMatch: 'http' is not a registered namespace
> ```
> 
> Thanks a lot.

Found the cause in LogoutView
```python
class LogoutView(View):
        ....
        if settings.CAS_LOGOUT_COMPLETELY:
            protocol = get_protocol(request)
            host = request.get_host()
            redirect_url = urllib_parse.urlunparse(
                (protocol, host, next_page, '', '', ''),
            )
            client = get_cas_client(request=request)
            print("protocol: {} host: {} redirect_url: {} client: {}".format(
                protocol, host, redirect_url, client
            ))
            return HttpResponseRedirect(client.get_logout_url(redirect_url))
```

`get_protocol` didn't bring the correct https maybe because it's behind proxy
`request.get_host()` bring the http://www.domain.com:433 instead of https://www.domain.com hence generate the wrong `redirect_url

This is my work around:

```python
from django.http import JsonResponse, HttpRequest, HttpResponse, HttpResponseRedirect
from django_cas_ng.views import LogoutView
from django_cas_ng.signals import cas_user_logout
from django_cas_ng.models import SessionTicket, ProxyGrantingTicket
from django_cas_ng.utils import get_protocol, get_cas_client
from django.contrib.auth import logout as auth_logout
from urllib import parse as urllib_parse


class MyLogoutView(LogoutView):
    def get(self, request: HttpRequest) -> HttpResponse:
        """
        Redirects to CAS logout page

        :param request:
        :return:
        """
        # next_page = clean_next_page(request, request.GET.get('next'))
        next_page = request.GET.get('next')
        # try to find the ticket matching current session for logout signal
        try:
            st = SessionTicket.objects.get(session_key=request.session.session_key)
            ticket = st.ticket
        except SessionTicket.DoesNotExist:
            ticket = None
        # send logout signal
        cas_user_logout.send(
            sender="manual",
            user=request.user,
            session=request.session,
            ticket=ticket,
        )
        # clean current session ProxyGrantingTicket and SessionTicket
        ProxyGrantingTicket.objects.filter(session_key=request.session.session_key).delete()
        SessionTicket.objects.filter(session_key=request.session.session_key).delete()
        auth_logout(request)

        if settings.CAS_LOGOUT_COMPLETELY:
            # protocol = get_protocol(request)
            force_ssl = getattr(settings, 'CAS_FORCE_SSL_SERVICE_URL', False)
            protocol = 'https' if force_ssl else get_protocol(request)
            # host = request.get_host()
            host = request.get_host().split(':')[0]
            redirect_url = urllib_parse.urlunparse(
                (protocol, host, next_page, '', '', ''),
            )
            client = get_cas_client(request=request)
            print("protocol: {} host: {} redirect_url: {} client: {}".format(
                protocol, host, redirect_url, client
            ))
            return HttpResponseRedirect(client.get_logout_url(redirect_url))

        return HttpResponseRedirect(next_page)

```

Problem temporary solved, but looking forward to the fix, thanks!

**Comment by bgroff** [comment]
I do not believe that this is an issue with django-cas-ng. You state that your application is behind a reverse proxy, so you will need to make sure that you are setting either the HTTP_X_FORWARDED_HOST or HTTP_HOST in the reverse proxy. Then in your settings you would need to set USE_X_FORWARDED_HOST=True in your settings.

You can see how Django figures out what to use here: https://github.com/django/django/blob/master/django/http/request.py#L106

If you have these headers set correctly then Django will be able to figure out the protocol correctly and you will not need your workaround.

**Comment by chunkai-meng** [comment]
👍 Thanks for giving the direction, I'll check the Nginx.

**Comment by bgroff** [comment]
If you are using Nginx, then your reverse proxy setup should look something like this: https://www.nginx.com/resources/wiki/start/topics/examples/likeapache/

Also if you are running Nginx on port 443 over http, you might just want to setup a TLS certificate. If you use Ubuntu, follow this guide for a free certificate: https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-ubuntu-18-04

**Comment by chunkai-meng** [comment]
thanks bgroff, problem solved by adding below setting to Nginx conf

```
proxy_set_header X-Forwarded-Porto $scheme;
```

---
Because, by adding this, the get_protocol() get the correct https from request header LogoutView give the correct redirect url.

bgroff is right this issue is not bug and can be closed

**Comment by aurelienboulet** [comment]
But why CAS_FORCE_SSL_SERVICE_URL = True is working only on login and not on logout ?
