### ISSUE TITLE
Django Rest Framework + Django CAS

### ISSUE THREAD

**Issue by agusmakmun** [django-cas-ng/django-cas-ng#251]
I've been tasked with adding [CAS authentication][1] to an existing Django app which uses the [Django Rest Framework][2]. 

Using [django-cas-ng][1] library I'm able to authenticate via CAS to the admin features of the Django framework, but I'm not sure how to go about authenticating the Django rest framework app via CAS; it's still authenticating via some custom authentication logic that the original developers added. If anyone has any insight or experience with this it would be much appreciated.

  [1]: https://djangocas.dev
  [2]: https://www.django-rest-framework.org

**Comment by mingchen** [comment]
You may use `python-cas` directly, see a Flask example https://djangocas.dev/blog/python-cas-flask-example/
It should be similar with DRF.

**Comment by agusmakmun** [comment]
@mingchen such as a great idea. But I'm little bit confuse how to implement that `python-cas` in header auth, such as: `Authorization: Token xxxx`, and how to logout that session.

**Comment by mingchen** [comment]
CAS don't use Authorization header, your server may require it after CAS login. You may need pass CAS token to your server through Authorization header in DRF. check your server api spec. 
to logout, just call cas logout api.
