### ISSUE TITLE
how to verify_ticket check proxy-ticket？

### ISSUE THREAD

**Issue by RyouZhang** [django-cas-ng/django-cas-ng#252]
my server is behind a cas-proxy gateway， so how to change the  verify_ticket url？

in python-cas， the client has attribute url_suffix，but django-cas-ng can‘t confiure it.

so I think is a bug，django-cas-ng can't support the proxy validate mode.

**Comment by mingchen** [comment]
Please checkout https://djangocas.dev/docs/latest/proxy-granting-ticket.html for how to verify Proxy Granting Ticket.

**Comment by RyouZhang** [comment]
I konw the proxy_callback, but my service is not the proxy. my django-server is the backend server. It must call cas proxyValidate to check the Proxy-Ticket.

**Comment by KunalSolanke** [comment]
@RyouZhang Did you find a work around?? 

I am also facing similar problem, where frontend is react and backend is django.So react will generate a proxy ticket using the cas server,for the django server but django server now needs to verify it against the cas server.Let me know if there is other way this can be implemented.
