### ISSUE TITLE
The documentation website can't be accessed.

### ISSUE THREAD

**Issue by max533** [django-cas-ng/django-cas-ng#255]
**Platform & Version**
Platform: Windows or Linux or Mac...
django-cas-ng: x.x.x
Django: x.x.x
Python: x.x.x
CAS Server Software and version: 

**Describe the bug**
The documentation website can't be accessed.

**To Reproduce**
1. Go to [django-cas-ng Github](https://github.com/django-cas-ng/django-cas-ng)
2. Click link [documentation](https://djangocas.dev/docs/latest/)

**Expected behavior**
The documentation website can be accessed.

**Screenshots**
<img width="604" alt="1" src="https://user-images.githubusercontent.com/25530573/84221527-04646d80-ab08-11ea-932a-df4070a99e8d.PNG">

**Additional context**
No

**Comment by mingchen** [comment]
Fixed. Caused by a temporal network issue.
