### ISSUE TITLE
SingleLogOut 

### ISSUE THREAD

**Issue by b4ldr** [django-cas-ng/django-cas-ng#288]
I have been trying debug the SingleLogOut functionality of this module and i'm struggling to find where its implemented.  I see refrence to it in the [readme ](https://github.com/django-cas-ng/django-cas-ng/blob/d7ea8559af3b8dfdc14a4549df8a6655daab8009/docs/signals.rst#django_cas_ngsignalscas_user_logout) but i don't see this class anywhere else in the code and in `views.py` i only see reference to [`sender=manual`](https://github.com/django-cas-ng/django-cas-ng/blob/d7ea8559af3b8dfdc14a4549df8a6655daab8009/django_cas_ng/views.py#L207).  can you provide a pointer?

Sorry if this is a basic questions quite not to familiar with django.  thanks

**Comment by KenWhitesell** [comment]
That readme entry doesn't say that it implements the Single Logout functionality of the CAS protocol, only that it fires a signal when the user has logged out. You are right - there is no actual implementation of the Single Logout facility that I can find, either. It's quite possible that the actual implementation needs to be handled within your application. (Note - I think the key here is that this is a _client_ package - I believe your SLO message would need to be sent to your CAS server.)

**Comment by b4ldr** [comment]
the readme states "Sent on user logout. Will be fired over manual logout or logout via CAS SingleLogOut query."

Im specifically interested in "[or] logout via CAS SingleLogOut query" which i assumed refereed to CAS sending its [SLO message](https://apereo.github.io/cas/5.1.x/installation/Logout-Single-Signout.html#slo-requests).  Either way if its not implmented that nothing to see here :).  I will look at seeing if i can send a PR

**Comment by mingchen** [comment]
SLO also need application implement logout. see [CAS Single Logout (SLO) Work Flow](https://djangocas.dev/blog/cas-single-logout-slo-work-flow/).

**Comment by KenWhitesell** [comment]
> the readme states "Sent on user logout. Will be fired over manual logout or logout via CAS SingleLogOut query."

Yes, the **signal** will be sent. It's up to you to listen for that signal and take some action based upon it.

**Comment by b4ldr** [comment]
> > the readme states "Sent on user logout. Will be fired over manual logout or logout via CAS SingleLogOut query."
> 
> Yes, the **signal** will be sent. It's up to you to listen for that signal and take some action based upon it. It doesn't say that django-cas-ng will _do_ anything with that signal.

Ack thanks, would this project welcome a PR that implements such  logic? or is it expected that this should be left up to the implementing apps.  To me it seems useful in this project but again still getting familiar with django.

Thanks
