### ISSUE TITLE
Mysql utf8 database issue since 4.2.0

### ISSUE THREAD

**Issue by pix106** [django-cas-ng/django-cas-ng#291]
**Platform & Version**
Platform: Linux
django-cas-ng: >= 4.2.0
Django: 3.2
Python: 3.8
CAS Server Software and version: 3

**Describe the bug**
The migration needed for django-cas-ng >= 4.2.0 fails on a utf8 mysql/mariadb database with error : 

> 1071, 'Specified key was too long; max key length is 3072 bytes'

It works with a "smaller" collation, such as latin_sweedish_ci, but it is supposed to work on utf8 databases too, isn't it ?

**To Reproduce**
1. use a utf8 mysql database
2. update django-cas-ng >=4.2.0
3. migrate
4. see "1071, 'Specified key was too long; max key length is 3072 bytes'"

**Expected behavior**
migration succeeds on a utf8 database

**Screenshots**

**Additional context**
mariadb server is debian stable

Thanks

**Comment by pix106** [comment]
No reaction to this bug ?

**Comment by fiterbek** [comment]
I have the same.

**Comment by matthewn** [comment]
I was also bit by this. Downgrading to 4.1.1 solved the issue.

**Comment by pix106** [comment]
Downgrading is more a temporary workaround than a solution :)

**Comment by pix106** [comment]
@mingchen any thoughts about this bug ?

**Comment by Xuexiang825** [comment]
any updates?

**Comment by fredfr94** [comment]
> I was also bit by this. Downgrading to 4.1.1 solved the issue.

Me too. Downgrading is fine.
Investigating, I found that my mariadb dislikes the varchar(1024) in following lines.
Hope this help.

```
$ python manage.py sqlmigrate  django_cas_ng 0002
--
-- Alter field session_key on proxygrantingticket
--
ALTER TABLE `django_cas_ng_proxygrantingticket` MODIFY `session_key` varchar(1024) NULL;
--
-- Alter field session_key on sessionticket
--
ALTER TABLE `django_cas_ng_sessionticket` MODIFY `session_key` varchar(1024) NOT NULL;
```

**Comment by pix106** [comment]
@nikolas
@mingchen
Would you please react to this bug ?
Thanks

**Comment by nikolas** [comment]
I use postgresql, not mysql/mariadb. It looks like you need to increase the max length of a db column.

**Comment by nikolas** [comment]
Interesting, so we added this migration recently: https://github.com/django-cas-ng/django-cas-ng/issues/291

Which seems to be conflicting with MySQL's max CHAR length of 30: https://dev.mysql.com/doc/refman/8.0/en/char.html

It seems like using the VARCHAR type isntead in MySQL would resolve an issue. I'm not familiar with using MySQL with Django - is there a way we can tell Django to use the more appropriate MySQL type in this case?

**Comment by nikolas** [comment]
@pix106 what collation are you using? Try using the extra-wide utf8 collation to accommodate this change, e.g.:

```
create database my_db character set utf8 collate utf8mb4;
```

See: https://stackoverflow.com/a/52180567/173630

**Comment by pix106** [comment]
@gregbaker Thanks !

Theoricaly it should be ok with this value.
I'll give this a try as soon as i can.

Thanks again !

**Comment by mateka** [comment]
We have faced the same issue and downgrade blocks using Django 4.

**Comment by crazyapril** [comment]
This means django-cas-ng 4.3.0 is NOT compatible with Django 4.

**Comment by fiterbek** [comment]
as this issue was closed as stale, this of course popped up again, see https://github.com/django-cas-ng/django-cas-ng/issues/317
