### ISSUE TITLE
djangocas.dev website links to old changelog

### ISSUE THREAD

**Issue by intgr** [django-cas-ng/django-cas-ng#292]
The django-cas-ng website at https://djangocas.dev/ has a "Releases" button, which links to https://djangocas.dev/docs/4.0/changelog.html -- but this documentation URL does not show the newest 4.1 releases

I think it should track the "latest" changelog: https://djangocas.dev/docs/latest/changelog.html

PS: I would submit a PR at https://github.com/django-cas-ng/django-cas-ng.github.io , but GitHub says that repository is empty :)

**Comment by mingchen** [comment]
Fixed.

Thanks for reporting this issue.
