### ISSUE TITLE
Invalid next URLs in login causes a server error

### ISSUE THREAD

**Issue by VinDuv** [django-cas-ng/django-cas-ng#299]
**Platform & Version**
Platform: Linux
django-cas-ng: 4.1.1 (waiting for #291 to be fixed before upgrading to 4.2.1)
Django: 3.2.6
Python: 3.7.3-2+deb10u3
CAS Server Software and version: MamaCas 2.4.0

**Describe the bug**
An incorrect `next` URL passed to the login view (absolute URL pointing to the wrong site) causes a `RedirectException("Non-local url is forbidden to be redirected to.")` to be raised, which is not caugh and ends up causing a 500 Server Error. 
(This assumes that `settings.CAS_CHECK_NEXT` is enabled, which should probably be the case in most circumstances)
Instead of causing a server error (which causes Django to send error emails), the login view should return a `HttpResponseBadRequest` response (since the request is indeed invalid).

**To Reproduce**
The issue is visible on the demo page:
Load https://django-cas-ng-demo.herokuapp.com/accounts/login?next=http://www.google.com/ ; it returns a “Server Error” page and a 500 HTTP error code.

**Expected behavior**
Loading the page with an incorrect next URL should return a 400 Bad request error page and not cause Django to send an error email.

**Comment by bgrantdev** [comment]
We are also having this issue.
