### ISSUE TITLE
Django >= 3.2.7 requires new migration script

### ISSUE THREAD

**Issue by fireinthehole** [django-cas-ng/django-cas-ng#304]
**Platform & Version**
Platform: Linux, Windows
django-cas-ng: 4.2.1
Django: 3.2.9
Python: 3.8.6
CAS Server Software and version: 

**Describe the bug**
When launching makemigrations command in a django project, it generates a migration script relative to django-cas-ng

**To Reproduce**
Inside a django project:
./manege.py makemigrations

**Expected behavior**
Generate migration scripts only in my django project, but not in django cas

**Screenshots**

**Additional context**
Here is the content of the migration:
```
\ # Generated by Django 3.2.9 on 2021-11-16 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_cas_ng', '0003_auto_20210813_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxygrantingticket',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sessionticket',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
```

**Comment by fireinthehole** [comment]
> Add any other context about the problem here.

Here is the migration content:

# Generated by Django 3.2.9 on 2021-11-16 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_cas_ng', '0003_auto_20210813_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxygrantingticket',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sessionticket',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
`
`

**Comment by JermaHuang** [comment]
I execute **python manage.py migrate django_cas_ng**, and it report:

**error django.db.utils.OperationalError: (1071, 'Specified key was too long; max key length is 3072 bytes')**

**Comment by corralien** [comment]
Add `DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'` in your `settings.py` file.

Check the documentation: [Customizing type of auto-created primary keys](https://docs.djangoproject.com/en/3.2/releases/3.2/#customizing-type-of-auto-created-primary-keys)
