### ISSUE TITLE
django.db.utils.OperationalError: (1071, 'Specified key was too long; max key length is 3072 bytes')

### ISSUE THREAD

**Issue by xiaozhi-cn** [django-cas-ng/django-cas-ng#317]
**Platform & Version**
Platform: Mac m2
django-cas-ng:  4.3
Django: 4.1
Python: 3.10
CAS Server Software and version: 

**Describe the bug**

django.db.utils.OperationalError: (1071, 'Specified key was too long; max key length is 3072 bytes')

causes by:  
1  django_cas_ng  migrate 
2 Applying django_cas_ng.0002_auto_20201023_1400...Traceback (most recent call last):
3 ticket = models.CharField(max_length=1024)

my plan：
ticket = models.TextField(max_length=1024)

**Comment by yzcheung** [comment]
Remove all migration files and re-execute makemigrations command can fix this issue on my side.

**Comment by cuuush** [comment]
as a temporary workaround, you can downgrade to mysql 5.7. this issue seems to apply to mysql 8

**Comment by cuuush** [comment]
the reason is due to mysql8 default character set being utf8mb4, which uses 4 bytes per character. The max length of the charfields is 1024 X 4 bytes which is greater than 3072. is there a reason why these fields need to be so large? CAS specification recommends supporting up to 256 characters.

**Comment by fiterbek** [comment]
https://github.com/gregbaker/django-cas-ng is a fork that fixes this, no idea why this hasn't been merged into a release since it is a known issue; i referenced the (very quickly marked as stale) original issue above

**Comment by alkmc** [comment]
I have the same problem on mySQL 5.7 so I don't think it's a mySQL 8.0 issue only.

**Comment by alkmc** [comment]
@mingchen could you possible look into this issue?
