### ISSUE TITLE
CAS_APPLY_ATTRIBUTES_TO_USER does not appear to add any attributes to user

### ISSUE THREAD

**Issue by paulgoulain** [django-cas-ng/django-cas-ng#328]
**Platform & Version**
Platform: Linux
django-cas-ng: 4.3.0
Django: 4.1
Python: 3.10
CAS Server Software and version: 3.0

**Describe the bug**
My CAS returns several fields (like departmentNumber or eduPersonAffiliation) that I'd like to access within my view. I set the CAS_APPLY_ATTRIBUTES_TO_USER setting to True in settings.py, but accessing the request.user in my views does not provide me with these fields. Is it normal ?

**To Reproduce**
Within any view functions:

```Python
def my_view(request):
    print(dir(request.user))
```

No differences wether CAS_APPLY_ATTRIBUTES_TO_USER is set to True or False.

**Expected behavior**

That a dict of the attributes returned by my CAS would be accessible

**Comment by newtondotcom** [comment]
Did you find answer or someone helped you ? merci
